
project_id = "uphgdwrwaizomnyuwfwr"

[functions.send-email]
verify_jwt = false

[functions.email-scheduler]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.ai-learning-assistant]
verify_jwt = false

[functions.test-connectivity]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = true

[functions.send-waitlist-email]
verify_jwt = false

[functions.send-challenge-email]
verify_jwt = false

[functions.send-creator-application-email]
verify_jwt = false

[functions.download-gis-tool]
verify_jwt = false
