
project_id = "uphgdwrwaizomnyuwfwr"

[functions.send-email]
verify_jwt = false

[functions.email-scheduler]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.ai-learning-assistant]
verify_jwt = false

[functions.test-connectivity]
verify_jwt = false
